apiVersion: v1
kind: PersistentVolume
metadata:
  name: aquadb-pv
  namespace: aqua-security
  labels:
    app: aqua-db
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/var/lib/aquadata/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aquadb-pvc
  namespace: aqua-security
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: aquadb-pv
  selector:
    matchLabels:
      app: aqua-db
---
apiVersion: v1
kind: Service
metadata:
  name: aqua-db
  namespace: aqua-security
  labels:
    app: aqua-db
spec:
  ports:
    - port: 5432
  selector:
    app: aqua-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-db
  namespace: aqua-security
spec:
  template:
    metadata:
      labels:
        app: aqua-db
      name: aqua-db
    spec:
      serviceAccount: aqua
      containers:
      - name: aqua-db
        image: registry.aquasec.com/database:4.0.rc9
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aqua-db
                key: password
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: aquadb-data-mount
        ports:
        - containerPort: 5432
      volumes:
      - name: aquadb-data-mount
        persistentVolumeClaim:
          claimName: aquadb-pvc
