apiVersion: v1
kind: Service
metadata:
  name: aqua-gateway
  namespace: aqua-security
  labels:
    app: aqua-gateway
spec:
  ports:
    - port: 3622
  selector:
    app: aqua-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-gateway
  namespace: aqua-security
spec:
  template:
    metadata:
      labels:
        app: aqua-gateway
      name: aqua-gateway
    spec:
      serviceAccount: aqua      
      containers:
      - name: aqua-gateway
        image: registry.aquasec.com/gateway:4.0
        env:
          - name: SCALOCK_GATEWAY_PUBLIC_IP
            value: aqua-gateway
          - name: SCALOCK_DBUSER
            value: "postgres"
          - name: SCALOCK_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_DBNAME
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: db_name
          - name: SCALOCK_DBHOST
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: db_host
          - name: SCALOCK_DBPORT
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: db_port
          - name: SCALOCK_AUDIT_DBUSER
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: audit_db_user
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_AUDIT_DBNAME
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: audit_db_name
          - name: SCALOCK_AUDIT_DBHOST
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: audit_db_host
          - name: SCALOCK_AUDIT_DBPORT
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: db_port
        ports:
        - containerPort: 3622
---
apiVersion: v1
kind: Service
metadata:
  name: aqua-web
  namespace: aqua-security
  labels:
    app: aqua-web
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: aqua-web-ssl
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: aqua-web

  selector:
    app: aqua-web
  type: LoadBalancer    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-web
  namespace: aqua-security
spec:
  template:
    metadata:
      labels:
        app: aqua-web
      name: aqua-web
    spec:
      serviceAccount: aqua
      containers:
      - name: aqua-web
        image: registry.aquasec.com/console:4.0
        env:
          - name: SCALOCK_DBUSER
            value: "postgres"
          - name: SCALOCK_DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_DBNAME
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: db_name
          - name: SCALOCK_DBHOST
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: db_host
          - name: SCALOCK_DBPORT
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: db_port
          - name: SCALOCK_AUDIT_DBUSER
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: audit_db_user
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_AUDIT_DBNAME
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: audit_db_name
          - name: SCALOCK_AUDIT_DBHOST
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: audit_db_host
          - name: SCALOCK_AUDIT_DBPORT
            valueFrom:
              configMapKeyRef:              
                name: postgres-connection-details
                key: audit_db_port
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
        ports:
        - containerPort: 8080
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
