apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-scanner
  namespace: aqua-security
spec:
  template:
    metadata:
      labels:
        app: aqua-scanner
      name: aqua-scanner
    spec:
      serviceAccount: aqua
      containers:
      - name: aqua-scanner
        image: registry.aquasec.com/scanner:4.0
        args: ["daemon", "--user", "<SCANNER_USER>", "--password", "$(SCANNER_PASSWORD)", "--host", "http://aqua-web:8080"]
        env:
        - name: SCALOCK_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: scanner-password
              key: password		    
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
        ports:
        - containerPort: 8080
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
